version: '3.4'

services:
  GTL.API:
    image: ${DOCKER_REGISTRY-}gtlapi
    build:
      context: .
      dockerfile: GTL.API/Dockerfile
    ports:
      - "5119:8080"
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development" 
      "ASPNETCORE_URL": "http://localhost"
      "ASPNETCORE_HTTP_PORT": "5119"
      "ConnectionStrings:Database": "Data Source=GTL.db,1433;Database=GTLDB;Application Name=GTL;Integrated Security=false;User ID=SA;Password=yourStrong(!)Password;TrustServerCertificate=True;"
    depends_on:
      - GTL.db
      
  GTL.db:
    container_name: GTL.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - 1433:1433
    volumes:
      - ./.containers/db:/var/lib/mssql/data
      