// <auto-generated />
using System;
using GTL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTL.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GTL.Domain.Models.BookBorrowingsEntity", b =>
                {
                    b.Property<Guid>("BooksBookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("books_book_id");

                    b.Property<Guid>("MembersMemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("members_member_id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2")
                        .HasColumnName("due");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("returned_date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("BooksBookId", "MembersMemberId")
                        .HasName("pk_book_borrowing_entities");

                    b.HasIndex("MembersMemberId")
                        .HasDatabaseName("ix_book_borrowing_entities_members_member_id");

                    b.ToTable("book_borrowing_entities", (string)null);
                });

            modelBuilder.Entity("GTL.Domain.Models.BookCatalogEntity", b =>
                {
                    b.Property<Guid>("BookCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_catalog_id");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("authors");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("edition");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("isbn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SubjectArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("subject_area");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("BookCatalogId")
                        .HasName("pk_book_catalog");

                    b.HasIndex("Authors")
                        .HasDatabaseName("ix_book_catalog_authors");

                    b.HasIndex("ISBN")
                        .HasDatabaseName("ix_book_catalog_isbn");

                    b.HasIndex("SubjectArea")
                        .HasDatabaseName("ix_book_catalog_subject_area");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_book_catalog_title");

                    b.ToTable("BookCatalog", "bookCatalog");
                });

            modelBuilder.Entity("GTL.Domain.Models.BookEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<Guid>("BookCatalogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_catalog_id");

                    b.Property<Guid>("CatalogBookCatalogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catalog_book_catalog_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<bool>("IsLendable")
                        .HasColumnType("bit")
                        .HasColumnName("is_lendable");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("BookId")
                        .HasName("pk_book");

                    b.HasIndex("CatalogBookCatalogId")
                        .HasDatabaseName("ix_book_catalog_book_catalog_id");

                    b.ToTable("Book", "book");
                });

            modelBuilder.Entity("GTL.Domain.Models.MemberEntity", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<string>("CampusAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campus_address");

                    b.Property<DateTime>("CardExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("card_expiration_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("home_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ssn");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("MemberId")
                        .HasName("pk_member");

                    b.ToTable("Member", "member");
                });

            modelBuilder.Entity("GTL.Domain.Models.BookBorrowingsEntity", b =>
                {
                    b.HasOne("GTL.Domain.Models.BookEntity", "Books")
                        .WithMany("Borrowings")
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_borrowing_entities_book_books_book_id");

                    b.HasOne("GTL.Domain.Models.MemberEntity", "Members")
                        .WithMany("Borrowings")
                        .HasForeignKey("MembersMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_borrowing_entities_member_members_member_id");

                    b.Navigation("Books");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GTL.Domain.Models.BookEntity", b =>
                {
                    b.HasOne("GTL.Domain.Models.BookCatalogEntity", "Catalog")
                        .WithMany("Books")
                        .HasForeignKey("CatalogBookCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_book_catalog_catalog_book_catalog_id");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("GTL.Domain.Models.BookCatalogEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("GTL.Domain.Models.BookEntity", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("GTL.Domain.Models.MemberEntity", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
